# Generated by Django 4.1.3 on 2022-11-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_task_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(default='', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
